name: Check pull request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  code_quality:
    name: Check code quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: make install-dev
      - run: make black-check
      - run: make isort-check
      - run: make flake8
      - run: make mypy
      - run: make pylint
      - run: make bandit
      - run: make pip-audit

  unit_tests:
    name: Run unit tests

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: make install-dev
      - run: make test

  version_check:
    name: Check version

    runs-on: ubuntu-latest

    if: ${{ github.base_ref == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check whether the version was updated
        run: |
          PUBLISHED_VERSION=$(curl --silent https://pypi.org/pypi/lbz/json | jq -r '.info.version')
          ACTUAL_VERSION=$(cat version)
          if [ "$PUBLISHED_VERSION" == "$ACTUAL_VERSION" ]; then
            echo "Update the Lambdalizator version before merging!"
            exit 1
          fi
