name: Publish to PyPI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  pypi:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Build package
        run: make build

      - name: Install dependencies
        run: pip install twine

      - name: Publish package
        run: make upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI }}
