name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  pypi:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"
      - run: make build-nocache
      - run: pip install -r requirements-deploy.txt
      - run: python -m twine upload --verbose dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI }}
